version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "33066:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
  redis:
    image: redis

